### ISSUE TITLE
Cannot read properties of null (reading 'getNorthEast')

### ISSUE THREAD

**Issue by alehano** [giorgiabosello/google-maps-react-markers#1]
I have this error after reloading page:

Uncaught TypeError: Cannot read properties of null (reading 'getNorthEast')
    at hj.<anonymous> (map.js:20:1)
    at _.M (js?libraries=places,geometry:131:320)
    at b (map.js:50:174)

It seems related to this issue
https://stackoverflow.com/questions/27812394/map-getbounds-weird-behaviour-uncaught-typeerror-cannot-read-property-getno

**Comment by giorgiabosello** [comment]
Please, provide a codesandbox with the error.

**Comment by alehano** [comment]
> 

Here is the link to sandbox https://codesandbox.io/embed/nostalgic-jasper-0bbcy9?fontsize=14&hidenavigation=1&theme=dark
