### ISSUE TITLE
[FEATURE] Auto zoom and focus to Info Window when click in a marker show it

### ISSUE THREAD

**Issue by RodrigoTomeES** [giorgiabosello/google-maps-react-markers#10]
**Is your feature request related to a problem? Please describe.**
If there is no autofocus, the content of the Info Window may be left out of the display. 

**Describe the solution you'd like**
Center the Info Window on the map when it is displayed

![Captura de pantalla 2022-12-02 a las 9 37 12](https://user-images.githubusercontent.com/13077343/205251160-eab89708-a2be-4893-8c8a-f791b8415ae4.jpg)

**Comment by giorgiabosello** [comment]
I cannot not do this within the library, I want it to maintain as light as possible.
You can do it by yourself by just adding a `mapRef.current.setCenter()` when clicking on the marker (`onClick`).
