### ISSUE TITLE
Drag handlers do not work

### ISSUE THREAD

**Issue by siriscmv** [giorgiabosello/google-maps-react-markers#102]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

I don't know how to solve the bug and I will provide an example.

### To Reproduce

Create a marker component like

```
<img
			draggable
			lat={lat}
			lng={lng}
			onClick={console.log}
			onDrag={console.log}
			onDragStart={console.log}
			onDragEnd={console.log}
			{...props}
		/>
```		

### Describe the Bug

Props such as `onDrag`, `onDragStart`, `onDragEnd`, `onChange` do not get called. Only `onClick` and `draggable` works

### Expected Behavior

Those props should work

**Comment by siriscmv** [comment]
@giorgiabosello `console.log` is a function, syntactic sugar for ` onDragStart={(e, { latLng }) => { console.log(e, latLng) }}`.

I dont see how my code is different from the commented out code in the readme

**Comment by siriscmv** [comment]
okay, I see that the code takes drag handlers from the props. It works if I pass them as props

**Comment by giorgiabosello** [comment]
Ok 🙂
