### ISSUE TITLE
some map options like `fullscreenControl` do not work

### ISSUE THREAD

**Issue by joeboe17** [giorgiabosello/google-maps-react-markers#103]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

I don't know how to solve the bug and I will provide an example.

### Link to the code that reproduces this issue

https://codesandbox.io/s/magical-alex-352wr5?file=/src/App.js

### To Reproduce

In the code snippet, you can see that setting the map option for `fullscreenControl` to `true` does not work.

### Describe the Bug

The map option `fullscreenControl` does not appear to work. I cannot get it to show on any map using Google Maps React Markers.

### Expected Behavior

When you set `fullscreenControl` to `true`, it should show in the top right corner of the Google map. Based on Google Map API documentation, it should even show by default, but it does not.

**Comment by giorgiabosello** [comment]
Hi @joeboe17 
Did you set the API key?
Without the API key, a small set of configs work. This is not controlled by me, but by Google itself.

**Comment by joeboe17** [comment]
Yes. In my project I have the API key set. With `fullscreenControl` set to `true` in the map options, the full screen control still does not show.

**Comment by giorgiabosello** [comment]
I really don't know what to do. Options are directly passed as they are to the Google Maps script.
So, `fullscreenControl` should work like zoomControl as stated in the official documentation.
Is `fullscreenControl` the only one option not working, or there are other ones?
```js
mapTypeControl: true,
scaleControl: true,
streetViewControl: true,
rotateControl: true,
fullscreenControl: true,
zoomControl: true
```

**Comment by joeboe17** [comment]
Nvm it appears to have been a problem on my side. 

The problem is with the `Permissions-Policy`. Our policy was `fullscreen=()` which means no element is allowed to go full screen. If Google Maps detects that it doesn't have that permission then it won't render the full screen button at all. The default for that policy is `fullscreen=(self)`, so just changing it to that allows for full screen functionality again.

We can close this issue, thanks!
