### ISSUE TITLE
onClick of the markers not working after add onClick listener to the map

### ISSUE THREAD

**Issue by tecsobs** [giorgiabosello/google-maps-react-markers#12]
**Describe the bug**
If a click event listener is added to the map the onClick of the markers will not work anymore, instead the listener of the map will be fired

**To Reproduce**
const onGoogleApiLoaded = ({ map, maps }) => {
    map.addListener('click', (e) => {
      //this is the only way to get real coords in fullscreen and normal screen
    })
  }

**Expected behavior**
Both onClick of the map and onClick of the marker should work

**Comment by giorgiabosello** [comment]
@tecsobs tey to raise the z-Indez of the markers.

**Comment by tecsobs** [comment]
i did and the event propagates to the map. With e.stopPropagation() fixed that
