### ISSUE TITLE
Version 2.0.1. window is not defined (SSR)

### ISSUE THREAD

**Issue by Borming** [giorgiabosello/google-maps-react-markers#123]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

Revert to version 2.0.0

### Link to the code that reproduces this issue

/

### To Reproduce

There is a bug with .cjs version of lib in version 2.0.1. 

ERROR : window is not defined.

### Describe the Bug

ERROR : window is not defined error trow when starting the app in node.js

### Expected Behavior

No error in version 2.0.0.

### Which browser are you using? (if relevant)

Chrome

**Comment by giorgiabosello** [comment]
Solved in [version 2.0.2](https://github.com/giorgiabosello/google-maps-react-markers/releases/tag/2.0.2)
Let me know if everything's right.

**Comment by Borming** [comment]
Works. Thanks :)
