### ISSUE TITLE
onChange callback not triggered

### ISSUE THREAD

**Issue by marcinincreo** [giorgiabosello/google-maps-react-markers#140]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

I don't know how to solve the bug and I will provide an example.

### Link to the code that reproduces this issue

/

### To Reproduce

Update to 2.0.5

### Describe the Bug

Callback is not fired when the map changes (center, zoom, bounds).

### Expected Behavior

No error in version 2.0.2

**Comment by giorgiabosello** [comment]
Fixed on 2.0.6. Thank you! Missed that.
