### ISSUE TITLE
Google link in bottom left corner doesn't update

### ISSUE THREAD

**Issue by Emauss** [giorgiabosello/google-maps-react-markers#147]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

None

### Link to the code that reproduces this issue

https://giorgiabosello.github.io/google-maps-react-markers/

### To Reproduce

See the link in demo. On each map occurs this behaviour.

### Describe the Bug

In the bottom left corner we have an img with google logo. This is certainly a link to the same place in google maps.
Issue is that link doesn't update on change map position. Only zoom is changing in this link.

### Expected Behavior

Link updates properly with map position like here in other package:
https://jsbin.com/ruwogapuke/1/edit?js,output

### Which browser are you using? (if relevant)

Chrome 118.0.5993.118

**Comment by giorgiabosello** [comment]
@Emauss did you check if this is reproduced on a Google Map with the API Key implemented?

**Comment by Emauss** [comment]
@giorgiabosello yes there's the same.

**Comment by giorgiabosello** [comment]
It appears `mapUrl` is updated only the first time. I can't find out why. 
`onChange` and `onIdle` events are triggering, and so is the overlay view. 

I will get into it. Any help debugging is appreciated.

**Comment by Emauss** [comment]
@giorgiabosello there's any new info in this case?

**Comment by giorgiabosello** [comment]
@Emauss I'm sorry, nope. I didn't had any chance to look at it. I should be able to check this within this week. 
I'll keep you posted.

**Comment by giorgiabosello** [comment]
@Emauss Fixed in version 2.0.7 :)
Let me know if everything works, working example [here](https://giorgiabosello.github.io/google-maps-react-markers/).

**Comment by Emauss** [comment]
@giorgiabosello It works! 
Thank you so much. :)
