### ISSUE TITLE
Disable Google script load

### ISSUE THREAD

**Issue by jacobclyne** [giorgiabosello/google-maps-react-markers#16]
**Is your feature request related to a problem? Please describe.**
I have a use case where I need to load Google API on pages where Map is not imported and the duplicate API load is not okay.

**Describe the solution you'd like**
A prop with a boolean to indicate the Google API script has already loaded, so there is no need to load again.

**Comment by giorgiabosello** [comment]
@jacobclyne you have now two props available to manage this:
- `loadScriptExternally`: set to `true` to disable internal script load.
- `status`: pass one of the supported strings to render the GoogleMap component (`idle`, `loading`, `ready`, `error`).

**Comment by jacobclyne** [comment]
Thanks a lot!
