### ISSUE TITLE
Using the API Key shows an error in the browser console

### ISSUE THREAD

**Issue by alexrohleder** [giorgiabosello/google-maps-react-markers#17]
**Describe the bug**

When rendering the map with an API key I get this error on my console:

```
Loading the Google Maps JavaScript API without a callback is not supported: https://developers.google.com/maps/documentation/javascript/url-params#required_parameters
```

**To Reproduce**

1. Render a map with an API key
2. See error on the browser console

**Suggested solution(s)**

Adding the `callback ` query string here should fix:
https://github.com/giorgiabosello/google-maps-react-markers/blob/76767785ea89ddfaf1997254b32cc5a9a3671675/src/hooks/useGoogleMaps.js#L9

We could store a user provided function into a safe global name and pass it as callback

**Comment by yveshwang** [comment]
An empty `noop` callback might do the trick?

**Comment by giorgiabosello** [comment]
Added a default `noop` function to `window.googleMapsCallback`. You can override it by passing `scriptCallback` to the `GoogleMap` component.
