### ISSUE TITLE
Draggable Marker: Cannot read properties of null (reading 'fromLatLngToDivPixel')

### ISSUE THREAD

**Issue by florian42** [giorgiabosello/google-maps-react-markers#175]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

I don't know how to solve the bug and I will provide an example.

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/damp-sunset-d3nqdt

### To Reproduce

Thank you for providing this library as an alternative to `google-react-map`.
While working with draggable markers, I ran into an issue. 
To reproduce, please have a look at the example in code sandbox and drag & drop the marker. Afterwards, even moving the mouse over the map shows the error.

### Describe the Bug

An error is displayed in the console:

```
Cannot read properties of null (reading 'fromLatLngToDivPixel')
TypeError: Cannot read properties of null (reading 'fromLatLngToDivPixel')
    at HTMLDivElement.<anonymous> (https://l9zzjq-3000.csb.app/static/js/bundle.js:42423:38)
```

### Expected Behavior

No error is displayed when dragging a marker

### Which browser are you using? (if relevant)

Chrome Version 120.0.6099.71 (Official Build) (arm64)

**Comment by giorgiabosello** [comment]
Hi @florian42 your codesandbox isn't working. Besides, I see you commented out lat/lng from the Marker. They are **required** props, otherwise Maps won't work. You can't have Maps children without lat/lng.

**Comment by florian42** [comment]
Hi @giorgiabosello, thank you for your response. I updated the code sandbox so the codesandbox error doesn't distract from the issue: https://codesandbox.io/p/sandbox/damp-sunset-d3nqdt

The uncommented props you saw are on the img component and not the marker. The marker does include the coordinates, since it's also displaying as intended.

I think this could be the source of the problem: https://stackoverflow.com/a/6657723/8014273

**Comment by abreurapha** [comment]
Hello folks, I'm also going through the same problem. I also confirm @florian42's implementation above.

I would like to thank you for the library, including @giorgiabosello, thank you very much!

**Comment by giorgiabosello** [comment]
Hi guys, could you please check if with the same implementation as in the repository docs, it works? Update to version 2.0.8.
Thanks.

**Comment by florian42** [comment]
It's working as intended. Thank you!
