### ISSUE TITLE
Zooming out shows map multiple times

### ISSUE THREAD

**Issue by awahab3109** [giorgiabosello/google-maps-react-markers#193]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

None

### Link to the code that reproduces this issue

https://www.npmjs.com/package/google-maps-react-markers

### To Reproduce

Zoom out of the map, you will see map repeating multiple times

### Describe the Bug

When we zoom out of the map, it gets repeated

### Expected Behavior

Map should not be zoomed out enough to show it multiple times

### Which browser are you using? (if relevant)

Google Chrome

**Comment by giorgiabosello** [comment]
@awahab3109 I'm sorry, but I can't reproduce the issue on my end. 
You didn't insert a reproduction link, but the link of the repository.
