### ISSUE TITLE
Switching to RTL direction will move markers position

### ISSUE THREAD

**Issue by Pacn91** [giorgiabosello/google-maps-react-markers#291]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

I don't know how to solve the bug and I will provide an example.

### Link to the code that reproduces this issue

https://giorgiabosello.github.io/google-maps-react-markers/

### To Reproduce

Using your [demo playground](https://giorgiabosello.github.io/google-maps-react-markers/), update your dom HTML tag by adding the dir attribute as `dir="rtl"`. The markers will change position.

![image](https://github.com/user-attachments/assets/c3c9be65-71df-4d43-b028-245f0b33b19e)

### Describe the Bug

With direction as 'RTL' the marker `lng` value is changed. The `lan` stayed the same. On your demo website, if we move the blue marker for any position, like this:
![image](https://github.com/user-attachments/assets/b8b06f26-a4af-4fed-bab0-939106c3a770)

and then change the dir from LTR to RTL we can see that all the markers changed position and if we move again the blue marker to the old position the `lng` value is quite diferent now.

![image](https://github.com/user-attachments/assets/d579322d-1922-4cf7-9312-47c6a7688403)

### Expected Behavior

Switching between 'LTR' and 'RTL' should not have an impact on the markers position

### Which browser are you using? (if relevant)

Chrome and Firefox

**Comment by giorgiabosello** [comment]
Hi @Pacn91 fixed in version 2.0.11. Verifiable also in the [demo playground](https://giorgiabosello.github.io/google-maps-react-markers/).
Let me know :)

**Comment by Pacn91** [comment]
It's perfect, thanks a lot @giorgiabosello  :)
