### ISSUE TITLE
Markers rerender on every occasion 

### ISSUE THREAD

**Issue by jacobclyne** [giorgiabosello/google-maps-react-markers#3]
**Describe the bug**
Try to add a simple animation on the Marker (scale: 0 => scale: 1), and move the map.

**To Reproduce**
1. Try to add a simple animation on the Marker (scale: 0 => scale: 1)
3. Add some state change on Map Change
2. Move the map
3. Animation works on every state update. Meaning markers rerender constantly

**Expected behavior**
Map and also Markers should not re-render this often.

**Example**
[https://codesandbox.io/s/gracious-cartwright-908qiz?file=/src/App.js](https://codesandbox.io/s/gracious-cartwright-908qiz?file=/src/App.js)

**Comment by giorgiabosello** [comment]
I've found the problem. This is connected to the fix for the issue #2.
I need to find a way to keep both of the functionalities.
If you have urgency, use version 1.0.4 till this is fixed.
