### ISSUE TITLE
Change map hybrid doesnot work

### ISSUE THREAD

**Issue by centratelemedia** [giorgiabosello/google-maps-react-markers#4]
**Describe the bug**
change road map to hybrid does not work

**To Reproduce**
```
{
	"mapTypeControl": true,
	"fullscreenControl": false,
	"maxZoom": 20,
	"minZoom": 3,
	"rotateControl": true,
	"scaleControl": false,
	"streetViewControl": true,
	"type": "road",
	"zoomControl": true,
}
```
change to 

```
{
	"mapTypeControl": true,
	"fullscreenControl": false,
	"maxZoom": 20,
	"minZoom": 3,
	"rotateControl": true,
	"scaleControl": false,
	"streetViewControl": true,
	"type": "hybrid",
	"zoomControl": true,
}
```

**Comment by giorgiabosello** [comment]
Please, provide a codesandbox example.
Options are not managed on the map component, but they are passed directly in the Google Maps Library.

**Comment by giorgiabosello** [comment]
Please, provide a codesandbox example.
Options are not managed on the map component, but they are passed directly to the Google Maps Library.

**Comment by giorgiabosello** [comment]
`mapTypeId` is the key of the option.
[See reference](https://developers.google.com/maps/documentation/javascript/maptypes?authuser=1#BasicMapTypes).
