### ISSUE TITLE
Cannot read properties of null (reading 'getNorthEast')

### ISSUE THREAD

**Issue by bradley-varol** [giorgiabosello/google-maps-react-markers#46]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### Describe the Bug

Looks like `onIdle()` fails to `getBounds()` 🤔  This doesn't break the map.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/19194140/232010095-2ae34775-54d0-4874-a1ca-5804bc32f24d.png">

Sorry I don't have a reproduction repo at the moment. Just though I'd make this issue for now.

**Comment by giorgiabosello** [comment]
Hi @bradley-varol, check if you replicate issue #1, otherwise, check if you have wrong coordinates. Usually bounds function fails for these reasons.
