### ISSUE TITLE
Support for passing a function for click events on the map

### ISSUE THREAD

**Issue by CriticalNameError** [giorgiabosello/google-maps-react-markers#49]
### Describe the feature you'd like to request

As far as I see there is no support for passing a function that will be executed for click events **on the map**. It would be useful, e.g. to un-select markers (there is support for onClick events for markers already...)

### Describe the solution you'd like

Pass functions for on-click events to the underlying google maps API

### Describe alternatives you've considered

I think it can be achieved in a direct way

**Comment by giorgiabosello** [comment]
Since version 1.2.2, you can now pass any supported event to the main div.
```js
<GoogleMap
  ...
  events={[
    {
      name: 'onClick',
      handler: (e) => console.log(e),
    }
  ]]
/>
```
