### ISSUE TITLE
Support for dragging Marker

### ISSUE THREAD

**Issue by wherehows** [giorgiabosello/google-maps-react-markers#78]
### Describe the feature you'd like to request

I think it would be great to have a feature where you can click on a marker to move it to a different location and then receive the address or coordinates of that new location.

So developer can pass "onDragStart" and "onDragEnd" Props with "isMarkerDraggable" prop that makes marker draggable

### Describe the solution you'd like

I know that marker is drawn by CustomOverlay and this approach is different from [making a Marker Instance which is draggable](https://dev.to/techsolutionstuff/google-map-with-draggable-marker-example-4j07)

I found a solution that might be useful [here](https://stackoverflow.com/questions/22127626/can-we-make-custom-overlays-draggable-on-google-maps-v3)

### Describe alternatives you've considered

Nothing comes to mind

**Comment by giorgiabosello** [comment]
Released in version 1.4.1. Let me know if anything comes up :)
