### ISSUE TITLE
[Installation Error] Errors appear when installing  `google-maps-react-markers` package using `yarn` and `npm`

### ISSUE THREAD

**Issue by regisrex** [giorgiabosello/google-maps-react-markers#85]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

I don't know how to solve the bug and I will provide an example.

### Link to the code that reproduces this issue

N/A

### To Reproduce

I just install the dependencies 
```cmd
> yarn add google-maps-react-markers
```
```cmd
> npm i google-maps-react-markers
```

![image](https://github.com/giorgiabosello/google-maps-react-markers/assets/94565752/5f9251cc-5ce7-44ee-8417-335df4aa0e79)

the same even on npm

### Describe the Bug

Both and yarn failed to install the dependency
Seems like it depends on `react-google-map-piker` package which might not be available current, I guess.

### Expected Behavior

Successful installation

**Comment by giorgiabosello** [comment]
This is weird. There's nothing on the code that refers to that package. 
Try deleting `node_modules` in your project folders and reinstalling?

**Comment by regisrex** [comment]
Found where the problem was, my bad!
Thanks for making this useful tool tho.
