### ISSUE TITLE
bounds changes every few weeks

### ISSUE THREAD

**Issue by TheMkrage** [giorgiabosello/google-maps-react-markers#94]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

I don't know how to solve the bug and I will provide an example.

### Link to the code that reproduces this issue

n/a

### To Reproduce

```
<GoogleMap
                defaultCenter={defaultProps.center}
                defaultZoom={defaultProps.zoom}
                onGoogleApiLoaded={onGoogleApiLoaded}
                onChange={(map: any) => {
                    const bounds = map.bounds;
// the shape of bounds changes every few week!
                    const minLat = (bounds.Va ?? bounds.Ua ?? bounds.Ia).lo;
                    const maxLat = (bounds.Va ?? bounds.Ua ?? bounds.Ia).hi;
                    const minLng = (bounds.Ha ?? bounds.Ga ?? bounds.Va).lo;
                    const maxLng = (bounds.Ha ?? bounds.Ga ?? bounds.Va).hi;
                }}
            >
```

### Describe the Bug

The shape of the bounds object changes. it used to be bounds.Va and bounds.Ha for lat and LNG respectively. It has changed twice over the last few months and crashes our app each time. 

### Expected Behavior

I'd expect the bounds.whatever to be consistent. That way we could rely on it

### Which browser are you using? (if relevant)

Chrome

**Comment by giorgiabosello** [comment]
@TheMkrage could it be related to the Maps API? This is very strange. Code hasn't changed.
Could you give me an example of the bounds objects?

**Comment by TheMkrage** [comment]
I wasn't converting the bounds to JSON and didn't realize I needed to. This is working for me now:

```
const bounds = map.bounds;

                    const { north, south, east, west } = bounds.toJSON();
                    ````

**Comment by giorgiabosello** [comment]
@TheMkrage It shouldn't be necessary. At the end of the README, you can see an example of how bounds are used.
If it's working, anyway, close the issue. Thank you.
